# Generated by Django 4.2.2 on 2023-06-21 12:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('Feedback', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('hosp_name', models.CharField(max_length=250)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('type', models.CharField(default='null', max_length=200)),
                ('total_beds', models.FloatField()),
                ('occupied_b', models.FloatField()),
                ('available', models.FloatField()),
                ('total_vent', models.FloatField()),
                ('used_venti', models.FloatField()),
                ('availabl_1', models.FloatField()),
                ('total_staf', models.FloatField()),
                ('geom', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(default='null', max_length=100)),
                ('product_price', models.FloatField()),
                ('product_type', models.CharField(default='null', max_length=100)),
                ('latx', models.FloatField(default=0)),
                ('longy', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('logger', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('visited_time', models.CharField(max_length=100)),
                ('description', models.CharField(default='null', max_length=200)),
                ('status', models.CharField(default='To be Valid', max_length=100)),
                ('hosp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Hospitals', to='logger.hospitals')),
            ],
            options={
                'db_table': 'Logger',
            },
        ),
    ]
